{
  desktopLib,
  ...
}:
{
  config = {
    home-manager.users = desktopLib.mkHome (user: user.custom.desktop.apps.librewolf.enable) (
      user:
      { config, lib, ... }:
      let
        extensions = [
          # duplicate-tabs-closer
          "jid0-RvYT2rGWfM8q5yWxIxAHYAeo5Qg@jetpack"
        ]
        ++ user.custom.desktop.apps.librewolf.extensions;
        settings = {
          "beacon.enabled" = false;
          "browser.startup.page" = 3;
          "browser.toolbars.bookmarks.visibility" = "never";
          "media.eme.enabled" = true;
          "media.gmp-widevinecdm.enabled" = true;
          "pdfjs.enableScripting" = false;
          "permissions.default.desktop-notification" = 2;
          "privacy.spoof_english" = 1;
          "sidebar.verticalTabs" = true;
        }
        // user.custom.desktop.apps.librewolf.settings;
      in
      {
        programs.librewolf = {
          enable = true;
          languagePacks = [ "ja" ];
          policies = {
            RequestedLocales = [ "ja" ];
            Preferences."intl.accept_languages" = "ja,ja-JP";

            ExtensionSettings = {
              "*" = {
                installation_mode = "blocked";
                blocked_install_message = "dotfiles で宣言していない拡張機能はインストールできません";
              };
            }
            // lib.genAttrs extensions (id: {
              installation_mode = "normal_installed";
              install_url = "https://addons.mozilla.org/firefox/downloads/latest/${id}/latest.xpi";
            });
          };
        };
        home.file."${config.xdg.configHome}/librewolf/librewolf/librewolf.overrides.cfg".text =
          # The first line of an autoconfig file is discarded, so start with a comment.
          ''
            // Generated by Home Manager.
          ''
          + lib.concatStringsSep "\n" (
            lib.mapAttrsToList (name: value: ''defaultPref("${name}", ${builtins.toJSON value});'') settings
          )
          + "\n";
        home.persistence."/persist".directories = [
          ".config/librewolf"
        ];
      }
    );
  };
}
